# Generated by Django 3.2.7 on 2021-10-09 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20211009_0451'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
