# Generated by Django 3.2.7 on 2021-10-09 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_portfolio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
