# Generated by Django 3.2.7 on 2021-10-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_image',
            field=models.ImageField(default='default.png', upload_to='media/skills'),
        ),
    ]
