# Generated by Django 3.2.7 on 2021-10-09 07:21

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('home', '0011_auto_20211009_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
