# Generated by Django 3.2.7 on 2021-10-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_remove_about_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='tag_line',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
