# Generated by Django 3.2.7 on 2021-10-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20211003_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='github_link',
            field=models.CharField(default='www.example.com', max_length=200),
        ),
        migrations.AddField(
            model_name='about',
            name='linkedin_link',
            field=models.CharField(default='www.example.com', max_length=200),
        ),
        migrations.AddField(
            model_name='about',
            name='phone',
            field=models.CharField(default=0, max_length=14),
        ),
        migrations.AddField(
            model_name='about',
            name='twitter_link',
            field=models.CharField(default='www.example.com', max_length=200),
        ),
    ]
